spring.application.name=sms
# ==============================================
# = Application Configuration
# ==============================================
server.port=8080
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=USER,ADMIN
# ==============================================
# = DataSource Configuration (PostgreSQL)
# ==============================================
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.username=postgres
spring.datasource.password=gayathri
#spring.datasource.url=jdbc:postgresql://employee-db:5432/employee_db

spring.datasource.url=jdbc:postgresql://sms_db:5432/sms_db


# ==============================================
# = JPA / Hibernate Configuration
# ==============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==============================================
# = Logging
# ==============================================
# Shows SQL statements and parameters in console (good for debugging)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=INFO
logging.level.com.yourorg.employeeprofilemanagement=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
