version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout

      # STEP 1: Build JAR
      - run:
          name: Build JAR
          command: mvn -B -DskipTests clean package

      # STEP 2: Enable Docker
      - setup_remote_docker

      # STEP 3: Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/sms-app:latest .

      # STEP 4: Push Docker image
      - run:
          name: Push Docker image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/sms-app:latest

workflows:
  build-docker-image:
    jobs:
      - build-and-push
